spring:
  application:
    name: dinner
  datasource:
    url: jdbc:postgresql://localhost:5432/dbdinner
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
